//19/02/2025 repeat batch 2pm
import javax.persistence.Cacheable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Cacheable
public class User {
	
	@Id
	@GeneratedValue // annotation field indicates autogenerated value
	 private int id;
	 private String name;
//	 @Column(unique=true ,nullable=false) //by default unique is false and nullable is true
	 private String username;
	 private String email;
	 private long phone;
//	 @Column(nullable=false)
	 private String password;
	 
	 private long adr;
	 

}
